language: python
python:
  - 3.6
  - 3.8
# install dependencies
install:
  - pip install -r requirements.txt
  - pip install pycodestyle

# run tests
script:
  - cd youthversity
  - python manage.py test backend
  - pycodestyle . --exclude migrations --ignore=E501,W504
