# Generated by Django 3.0.4 on 2020-03-21 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('edited', models.BooleanField()),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_in_subjects', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('edited', models.BooleanField()),
                ('type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('visibility', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=2)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Feed')),
                ('friends', models.ManyToManyField(related_name='_user_friends_+', to='backend.User')),
                ('saved_posts', models.ManyToManyField(to='backend.Post')),
            ],
        ),
        migrations.CreateModel(
            name='ViolationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('answer', models.TextField(null=True)),
                ('done', models.BooleanField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violation_reports_authored', to='backend.User')),
                ('processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violation_reports_processed', to='backend.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('students', models.ManyToManyField(related_name='school_classs_teaching', to='backend.User')),
                ('teachers', models.ManyToManyField(related_name='school_classs_member', to='backend.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_authored', to='backend.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Subject'),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(to='backend.User'),
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('edited', models.BooleanField()),
                ('type', models.CharField(max_length=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentreply_authored', to='backend.User')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='backend.Comment')),
                ('upvotes', models.ManyToManyField(to='backend.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_authored', to='backend.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='backend.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(to='backend.User'),
        ),
    ]
