# Generated by Django 3.0.4 on 2020-03-21 14:25

from django.db import migrations

DEFAULT_SUBJECTS = [
    "Naturwissenschaften", "Physik", "Chemie", "Mathe", "Biologie",
    "Sprachen", "Englisch", "Deutsch", "Französisch", "Spanisch", "Latein", "Altgriechisch",
    "Gesellschaft", "Geschichte", "Politik", "Wirtschaft", "Geographie", "Sozialkunde",
    "Technik", "Informatik",
    "Musik",
    "Kunst",
    "Sonstige"
]


def create_subjects(apps, schema_editor):
    Subject = apps.get_model('backend', 'Subject')

    for subj in DEFAULT_SUBJECTS:
        s = Subject(name=subj)
        s.save()


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0002_auto_20200321_1425'),
    ]

    operations = [
        migrations.RunPython(create_subjects)
    ]
