# Generated by Django 3.0.4 on 2020-03-21 14:25

from django.db import migrations

DEFAULT_SUBJECTS = {
    "Naturwissenschaften": [
        "Physik"
        "Chemie"
        "Mathe"
        "Biologie"
        "Sonstige"
    ],

    "Sprachen": [
        "Englisch"
        "Deutsch"
        "Französisch"
        "Spanisch"
        "Latein"
        "Altgriechisch"
        "Sonstige"
    ],

    "Gesellschaft": [
        "Geschichte"
        "Politik"
        "Wirtschaft"
        "Geographie"
        "Sozialkunde"
        "Sonstige"
    ],

    "Geisteswissenschaften": [
        "Philosophie"
        "Religion"
    ],

    "Technik": [
        "Informatik"
        "Sonstige"
    ],

    "Musik": [],

    "Kunst": [],

    "Sport": [],

    "Sonstige": [],
}



def create_subjects(apps, schema_editor):
    Subject = apps.get_model('backend', 'Subject')

    for subj, ssubs in DEFAULT_SUBJECTS.items():
        s = Subject(name=subj)
        s.save()
        for ssub in ssubs:
            ss = Subject(name=subj, parent=s)
            ss.save()


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0002_subject_parent'),
    ]

    operations = [
        migrations.RunPython(create_subjects)
    ]
