# Generated by Django 3.0.4 on 2020-03-21 14:25

from django.db import migrations

DEFAULT_SUBJECTS = [
    "Geisteswissenschaften", "Sport", 
]


def create_subjects(apps, schema_editor):
    Subject = apps.get_model('backend', 'Subject')

    for subj in DEFAULT_SUBJECTS:
        s = Subject(name=subj)
        s.save()


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0004_auto_20200321_2236'),
    ]

    operations = [
        migrations.RunPython(create_subjects)
    ]
