# Generated by Django 3.0.4 on 2020-03-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_create_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationreport',
            name='content_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='violationreport',
            name='flagged_type',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
