# Generated by Django 3.0.4 on 2020-03-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_post_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
